apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-martianbank
  labels:
    {{- include "martianbank.labels" . | nindent 4 }}
data:
    DB_URL: {{ .Values.DB_URL | default "mongodb://root:example@mongodb:27017" | quote }}
    JWT_SECRET: {{ .Values.JWT_SECRET | default "" | quote }}